Repository Firelods/DecheTri, pull requests merged in 2024-06, with the labels that each got.

#130 💄 add an icon
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/dechettri_icon.png
  app/src/main/res/drawable/ic_dashboard_black_24dp.xml
  app/src/main/res/drawable/ic_home_black_24dp.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_notifications_black_24dp.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: UI

#129 :white_check_mark: orange icon
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteMapFragment.java
  app/src/main/res/drawable/waste_to_pick.xml
Labels: enhancement, UX

#131 Fix: map refresh
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/taskslist/TasksFromWasteListAdapter.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/taskslist/TasksListFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteDialogFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteDialogListener.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteMapFragment.java
Labels: bug

#75 Adding the notification
  app/src/main/AndroidManifest.xml
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/flux/AnnouncementList.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/waste/WasteList.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/IFluxUpdateable.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/NewAnnouncementFragmentDialog.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/CreateNotification.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/CreateNotificationFactory.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/DeleteNotification.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/DeleteNotificationFactory.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/INotification.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/ItineraryNotification.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/ItineraryNotificationFactory.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/NotificationFactory.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/NotificationHelper.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/NotificationPermissionCallback.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/NotificationType.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/ReportNotification.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/ReportNotificationFactory.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/TaskCompletedNotification.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/TaskCompletedNotificationFactory.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/statistics/StatisticsFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/taskslist/TasksListFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteDialogFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteMapFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastereport/WasteDetailsReportFragment.java
  app/src/main/res/layout/fragment_waste_dialog.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#134 Ajout de la description pour le dialogue des déchets
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteDialogFragment.java
  app/src/main/res/layout/fragment_waste_dialog.xml
Labels: enhancement
