Repository Firelods/DecheTri, pull requests merged in 2024-05, with the labels that each got.

#56 Ajout des user_id dans les SharedPreferences lors du choix du du role
  app/src/main/java/etu/seinksansdoozebank/dechetri/RoleChoiceActivity.java
  app/src/main/res/values/strings.xml
Labels: enhancement

#52 Corrections des boutons de la bottomModal sur la map
  app/src/main/java/etu/seinksansdoozebank/dechetri/controller/api/APIController.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteDialogFragment.java
  app/src/main/res/layout/fragment_waste_dialog.xml
Labels: enhancement

#60 Retrait de la popup de confirmation de deconnexion (cimer Marco)
  app/src/main/java/etu/seinksansdoozebank/dechetri/MainActivity.java
Labels: enhancement

#55 Ajout des données dans l'application en utilisant l'api
  app/build.gradle.kts
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/flux/AnnouncementList.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/flux/AnnouncementListObserver.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/task/Task.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/task/TaskList.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/waste/Waste.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/waste/WasteList.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxAdapter.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/taskslist/TasksListAdapter.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/taskslist/TasksListFragment.java
  app/src/main/res/layout/fragment_flux.xml
  app/src/main/res/layout/fragment_tasks_list.xml
  app/src/main/res/layout/item_flux.xml
  app/src/main/res/layout/item_taskslist.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#42 Ajout de l'écran de confirmation de suppression d'un message
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
  app/src/main/res/values/strings.xml
Labels: enhancement

#36 Fonctionnalité de l'appareil photo et de la pellicule
  app/src/main/AndroidManifest.xml
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/dashboard/DashboardFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/dashboard/DashboardViewModel.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/home/HomeFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/home/HomeViewModel.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/NotificationsFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/NotificationsViewModel.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/taskslist/TasksListViewModel.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/Waste.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteList.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteMapViewModel.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastereport/LocationChoiceFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastereport/WasteDetailsReportFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastereport/WasteReportFragment.java
  app/src/main/res/drawable/ic_dashboard_black_24dp.xml
  app/src/main/res/drawable/ic_home_black_24dp.xml
  app/src/main/res/drawable/ic_notifications_black_24dp.xml
  app/src/main/res/layout/activity_addition_news.xml
  app/src/main/res/layout/activity_clicked_waste_map.xml
  app/src/main/res/layout/activity_deconnexion.xml
  app/src/main/res/layout/activity_deletion_news.xml
  app/src/main/res/layout/activity_flux.xml
  app/src/main/res/layout/activity_report_waste_details.xml
  app/src/main/res/layout/activity_statistics.xml
  app/src/main/res/layout/activity_tasks_list.xml
  app/src/main/res/layout/activity_waste_confirmation_location.xml
  app/src/main/res/layout/activity_waste_details.xml
  app/src/main/res/layout/activity_waste_details_employee.xml
  app/src/main/res/layout/activity_waste_location.xml
  app/src/main/res/layout/activity_waste_map.xml
  app/src/main/res/layout/activity_waste_picture.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_notifications.xml
  app/src/main/res/layout/fragment_waste_details_report.xml
  app/src/main/res/layout/fragment_waste_report.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: enhancement

#68 :ambulance: deleted empty files
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/dashboard/DashboardFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/dashboard/DashboardViewModel.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/home/HomeFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/home/HomeViewModel.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/NotificationsFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/notifications/NotificationsViewModel.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/taskslist/TasksListViewModel.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteMapViewModel.java
  app/src/main/res/layout/activity_addition_news.xml
  app/src/main/res/layout/activity_clicked_waste_map.xml
  app/src/main/res/layout/activity_deconnexion.xml
  app/src/main/res/layout/activity_deletion_news.xml
  app/src/main/res/layout/activity_flux.xml
  app/src/main/res/layout/activity_report_waste_details.xml
  app/src/main/res/layout/activity_tasks_list.xml
  app/src/main/res/layout/activity_waste_confirmation_location.xml
  app/src/main/res/layout/activity_waste_details.xml
  app/src/main/res/layout/activity_waste_details_employee.xml
  app/src/main/res/layout/activity_waste_location.xml
  app/src/main/res/layout/activity_waste_map.xml
  app/src/main/res/layout/activity_waste_picture.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_notifications.xml
Labels: bug

#66 :bug: Fix onDetach map on null reference
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastereport/LocationChoiceFragment.java
Labels: bug

#73 :white_check_mark: added imageview to waste report fragment
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastereport/WasteReportFragment.java
  app/src/main/res/drawable/depotimage.xml
  app/src/main/res/layout/fragment_waste_report.xml
Labels: enhancement

#78 Changement du formulaire pour coller au consigne de Marco
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/NewAnnouncementFragmentDialog.java
  app/src/main/res/drawable/baseline_info_24.xml
  app/src/main/res/drawable/border_button.xml
  app/src/main/res/drawable/outline_cancel_24.xml
  app/src/main/res/layout/add_announcement.xml
  app/src/main/res/layout/fragment_new_announcement_dialog.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, UX

#83 Fix: refresh layout
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/taskslist/TasksListFragment.java
Labels: bug

#74 Adding the waste on the map
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/flux/AnnouncementList.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/observable/Observable.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/waste/WasteList.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/waste/WasteListObservable.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/waste/WasteType.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteDialogFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteMapFragment.java
  app/src/main/res/drawable/baseline_refresh_24.xml
  app/src/main/res/layout/fragment_waste_dialog.xml
  app/src/main/res/layout/fragment_waste_map.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#71 :lipstick: make the validatebutton in position fixed,
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastereport/LocationChoiceFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastereport/WasteDetailsReportFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastereport/WasteReportFragment.java
  app/src/main/res/layout/fragment_waste_details_report.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#79 Déplacement du bouton "+" d'ajout d'annonce dans la toollbar
  app/src/main/java/etu/seinksansdoozebank/dechetri/MainActivity.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastereport/WasteDetailsReportFragment.java
  app/src/main/res/drawable/baseline_add_24.xml
  app/src/main/res/drawable/baseline_add_circle_outline.xml
  app/src/main/res/layout/fragment_flux.xml
  app/src/main/res/layout/fragment_waste_details_report.xml
  app/src/main/res/menu/action_bar_menu.xml
Labels: UX

#93 correction du crash en cas d'erreur d'update de la liste d'annonces
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/flux/AnnouncementList.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
Labels: bug

#95 Affichage d'un toast en cas d'erreur dans la récupération des déchets
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/waste/WasteList.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteMapFragment.java
Labels: bug

#86 :bug: Fix keyboard resizing
  app/src/main/java/etu/seinksansdoozebank/dechetri/MainActivity.java
Labels: bug

#105 Ajout de la confirmation de suppression de déchet
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteDialogFragment.java
  app/src/main/res/values/strings.xml
Labels: enhancement

#107 Fix/margin button flux
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
  app/src/main/res/layout/fragment_flux.xml
Labels: bug, UX

#111 Feature/assign spinner
  app/src/main/java/etu/seinksansdoozebank/dechetri/controller/api/APIController.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/user/Role.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/user/User.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/waste/Waste.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteDialogFragment.java
  app/src/main/res/layout/fragment_waste_dialog.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#109 :goal_net: catch error of adress fetching
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastereport/WasteDetailsReportFragment.java
Labels: enhancement

#113 :white_check_mark: added labal no task assigned
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/taskslist/TasksListFragment.java
  app/src/main/res/layout/fragment_tasks_list.xml
Labels: enhancement, UX

#114 Feature task onclick
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/taskslist/TasksListAdapter.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteMapFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastereport/LocationChoiceFragment.java
Labels: enhancement

#87 Feature/statistics
  app/build.gradle.kts
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/flux/AnnouncementList.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/waste/Waste.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/waste/WasteList.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/waste/WasteListObserver.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/statistics/StatisticsFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteMapFragment.java
  app/src/main/res/layout/fragment_statistics.xml
  app/src/main/res/values/strings.xml
  gradle.properties
Labels: enhancement

#115 Feature/unassigned screen
  app/src/main/java/etu/seinksansdoozebank/dechetri/MainActivity.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/controller/api/APIController.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/taskslist/PersonnalTaskList.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/taskslist/TasksFromWasteListAdapter.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/taskslist/TasksListFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/taskslist/UnassignedTaskList.java
  app/src/main/res/drawable/baseline_checklist_24.xml
  app/src/main/res/drawable/baseline_view_list_24.xml
  app/src/main/res/drawable/outline_format_list_bulleted_add_24.xml
  app/src/main/res/layout/fragment_personnal_task_list.xml
  app/src/main/res/layout/fragment_tasks_list.xml
  app/src/main/res/layout/fragment_unassigned_task_list.xml
  app/src/main/res/menu/menu_item_personnal_task_list.xml
  app/src/main/res/menu/menu_item_unassigned_task_list.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/navigation/nav_admin.xml
  app/src/main/res/navigation/nav_employee.xml
  app/src/main/res/navigation/nav_manager.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#117 :white_check_mark: show only buttons for the right person
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteDialogFragment.java
Labels: enhancement, UX

#128 Retrait du bouton Annuler dans le choix de la photo
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastereport/WasteReportFragment.java
  app/src/main/res/layout/fragment_waste_report.xml
Labels: UX

#127 Correction de la marge du fragment FLux
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
  app/src/main/res/layout/fragment_flux.xml
Labels: UI

#119 Fix le signalement envoie maintenant le nom en tant que nom et pas la description
  app/src/main/java/etu/seinksansdoozebank/dechetri/controller/api/APIController.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/waste/Waste.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/waste/WasteDTO.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastereport/WasteDetailsReportFragment.java
Labels: bug

#126 Changement de Activités en Annonces
  app/src/main/res/layout/fragment_flux.xml
  app/src/main/res/layout/fragment_new_announcement_dialog.xml
  app/src/main/res/values/strings.xml
Labels: UX

#96 Amélioration de l'affichage de la date pour l'utilisateur
  app/src/main/java/etu/seinksansdoozebank/dechetri/controller/api/APIController.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxAdapter.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/NewAnnouncementFragmentDialog.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/taskslist/TasksListFragment.java
  app/src/main/res/layout/item_flux.xml
Labels: enhancement

#116 :globe_with_meridians: Translate all errors in french
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/flux/AnnouncementList.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/model/waste/WasteList.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/NewAnnouncementFragmentDialog.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/taskslist/TasksListFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteDialogFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastereport/WasteDetailsReportFragment.java
  app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastereport/WasteReportFragment.java
  app/src/main/res/layout/fragment_tasks_list.xml
  app/src/main/res/values/strings.xml
Labels: constraint
